export const LOGIN_REQUEST = "LOGIN_REQUEST";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FALURE = "LOGIN_FALURE";
export const LOGOUT = "LOGOUT";
export const FALHA = "FALHA";
export const PERSIST_TOKEN = "PERSIST_TOKEN";

export const EMPRESA_REQUEST = "EMPRESA_REQUEST";
export const EMPRESA_SUCCESS = "EMPRESA_SUCCESS";
export const EMPRESA_FALURE = "EMPRESA_FALURE";

export const EMPRESA_EDITAR_REQUEST = "EMPRESA_EDITAR_REQUEST";
export const EMPRESA_EDITAR_SUCCESS = "EMPRESA_EDITAR_SUCCESS";
export const EMPRESA_EDITAR_FALURE = "EMPRESA_EDITAR_FALURE";

export const EMPRESA_BUSCAR_REQUEST = "EMPRESA_BUSCAR_REQUEST";
export const EMPRESA_BUSCAR_SUCCESS = "EMPRESA_BUSCAR_SUCCESS";
export const EMPRESA_BUSCAR_FALURE = "EMPRESA_BUSCAR_FALURE";

export const USUARIO_BUSCAR_REQUEST = "USUARIO_BUSCAR_REQUEST";
export const USUARIO_BUSCAR_SUCCESS = "USUARIO_BUSCAR_SUCCESS";
export const USUARIO_BUSCAR_FALURE = "USUARIO_BUSCAR_FALURE";

export const EMPRESA_DELETAR_REQUEST = "EMPRESA_DELETAR_REQUEST";
export const EMPRESA_DELETAR_SUCCESS = "EMPRESA_DELETAR_SUCCESS";
export const EMPRESA_DELETAR_FALURE = "EMPRESA_DELETAR_FALURE";

export const EMPRESA_CRIAR_COM_FOTO = "EMPRESA_CRIAR_COM_FOTO";
export const EMPRESA_EDITAR_COM_FOTO = "EMPRESA_EDITAR_COM_FOTO";

export const ARQUIVO_CRIAR_REQUEST = "ARQUIVO_CRIAR_REQUEST";
export const ARQUIVO_CRIAR_SUCCESS = "ARQUIVO_CRIAR_SUCCESS";
export const ARQUIVO_CRIAR_FALURE = "ARQUIVO_CRIAR_FALURE";

export const ARQUIVO_EDITAR_REQUEST = "ARQUIVO_EDITAR_REQUEST";
export const ARQUIVO_EDITAR_SUCCESS = "ARQUIVO_EDITAR_SUCCESS";
export const ARQUIVO_EDITAR_FALURE = "ARQUIVO_EDITAR_FALURE";

export const ARQUIVO_BUSCAR_REQUEST = "ARQUIVO_BUSCAR_REQUEST";
export const ARQUIVO_BUSCAR_SUCCESS = "ARQUIVO_BUSCAR_SUCCESS";
export const ARQUIVO_BUSCAR_FALURE = "ARQUIVO_BUSCAR_FALURE";

export const ARQUIVO_DOWNLOAD_REQUEST = "ARQUIVO_DOWNLOAD_REQUEST";
export const ARQUIVO_DOWNLOAD_SUCCESS = "ARQUIVO_DOWNLOAD_SUCCESS";
export const ARQUIVO_DOWNLOAD_FALURE = "ARQUIVO_DOWNLOAD_FALURE";

export const ARQUIVO_DELETAR_REQUEST = "ARQUIVO_DELETAR_REQUEST";
export const ARQUIVO_DELETAR_SUCCESS = "ARQUIVO_DELETAR_SUCCESS";
export const ARQUIVO_DELETAR_FALURE = "ARQUIVO_DELETAR_FALURE";

// ----------